---
dataset: "imbalancedMG"
d: 8
n: 20000
k:
  - 5
r: 0.01
m: 4096
intersection_method: 'fmsketch'
local_solver: 'lsh_clustering'
#local_branching_per_dim: 2
normalize: 'True'
local_cluster_budget:
  - 0.5
local_k:
#  - 'auto'
  - 5
T:
  - 2
  - 4
eps:
  - 0.5
  - 1
  - 2
  - 3
  - 4
  - 5